name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]


jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push adb
        uses: docker/build-push-action@v3
        with:
          context: ./adb
          push: true
          tags: nakabonne/adb:1.0
          platforms: linux/amd64

      - name: Build and push nettools
        uses: docker/build-push-action@v3
        with:
          context: ./nettools
          push: true
          tags: nakabonne/nettools:v1.0
          platforms: linux/amd64
